### ISSUE TITLE
Automatic GitHub Issue Labels no Worky

### ISSUE THREAD

**Issue by jaswrks** [websharks/osa#1]
It looks like GitHub changed the New Issue interface and labels panel since I worked on the script that handles automatic labels for new KB articles. I just wanted to document this here so we can try to get this working again soon. This impacts Typinator shortcuts:
- `.wskby`
- `.wskba..`

Referencing: https://github.com/websharks/osa/blob/000000-dev/libraries/utils/chrome.js#L125

![2015-03-06_16-43-20](https://cloud.githubusercontent.com/assets/1563559/6539422/49d4dc44-c420-11e4-9ac8-a3dbe5005901.png)

**Comment by raamdev** [comment]
@jaswsinc Yep. I thought that was just me or a quirk in my browser (I run Google Canary, which is the bleeding edge of Chrome), but I yeah, I'm experiencing that too.

**Comment by jaswrks** [comment]
> I run Google Canary, which is the bleeding edge of Chrome

Copy that. Most of the OSA libs currently look for `com.google.Chrome`. Canary is `com.google.Chrome.canary`. I'm guessing none of the Chrome-based tools in the OSA library are working for you then. I'll open a separate issue for this so we can try to add compatibility for Canary also.

**Comment by jaswrks** [comment]
This has been resolved. Referencing: https://github.com/websharks/osa/releases/tag/150307

**Comment by jaswrks** [comment]
@raamdev If you can change `.wskby` to the following, so it uses OSA libs instead of the old scripts, then I can just delete the `.wskba..` shortcut to avoid having it duplicated.

``````
{{Title=?KB Article Title}}{{Title}}{tab}---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: {{Title}}
categories: {{?Categories}}
tags: {{?Tags}}
author: {{?Author}}
github-issue: {{GitHubIssue={Scripts/wsOSA chrome/next-github-issue-url}}}{{GitHubIssue}}
```
---

{Scripts/wsOSA chrome/set-github-issue-labels}{^}
``````

**Comment by raamdev** [comment]
> This has been resolved. Referencing: https://github.com/websharks/osa/releases/tag/150307

Woohoo! Thanks for adding support for Canary. :-)

> If you can change .wskby to the following, so it uses OSA libs instead of the old scripts, then I can just delete the .wskba.. shortcut to avoid having it duplicated.

Done. Thank you! You just need to `git pull` on your local `typinator-sets` repo to get those changes (assuming the Typinator symlinks point to this repo, that's all you should need to do... maybe restart Typinator).
