### ISSUE TITLE
Merge WS Commander Into OSA Libs?

### ISSUE THREAD

**Issue by jaswrks** [websharks/osa#4]
Related to https://github.com/websharks/osa/issues/3
## If We Do This; Actions That Need To Occur?
- [ ] Take the existing tools from the WS Commander project and bring those ideas into the OSA framework; making them a part of the OSA project, and removing the need for us to maintain the WS Commander project, since it was started by Bruce who is no longer with us.

**Comment by raamdev** [comment]
THe WS Commander currently has the following tools:
- GitHub Next Issue URL
- iDoneThis Command-Line interface
- CSS/JS Minification tool

The first one (GitHub Next Issue URL) is already taken care of by the OSA framework. I haven't found a use for the iDoneThis command-line interface, as I use Slack for posting to iDoneThis, and I haven't found any need to use the CSS/JS Minification tool.

Note that all of these tools are using Node, so bringing them over to the OSA framework would mean either adding Node as a requirement or rewriting the tools from scratch.

I'm not seeing anything we _need_ to merge into the OSA framework here.

**Comment by jaswrks** [comment]
@raamdev writes...

> I'm not seeing anything we need to merge into the OSA framework here.

Copy that. Thanks! I'll close this then :-)
